running run_2_ml_params_noRFE_pc.py ....
Fixed EX_tDHNACOA(e)
vegan
Fixed EX_tDHNACOA(e)
... normalizing raw ASV abundances to fractions, dropping samples with 0 total abundances
# of genus in model and not filterd out of QA/QC: 50, # of genus not in model:0


--------------------------------------------------------------------------------
LokyProcess-33 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ekavvas/.conda/envs/mb_py385/lib/python3.8/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 199, in <module>
    process_obj = pickle.load(from_parent)
  File "/home/ekavvas/.conda/envs/mb_py385/lib/python3.8/site-packages/joblib/externals/loky/backend/synchronize.py", line 122, in __setstate__
    self._semlock = _SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-34 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ekavvas/.conda/envs/mb_py385/lib/python3.8/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 199, in <module>
    process_obj = pickle.load(from_parent)
  File "/home/ekavvas/.conda/envs/mb_py385/lib/python3.8/site-packages/joblib/externals/loky/backend/synchronize.py", line 122, in __setstate__
    self._semlock = _SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory


--------------------------------------------------------------------------------
